// Generated by purs version 0.15.10
import * as Codec_Json_Unidirectional_Value from "../Codec.Json.Unidirectional.Value/index.js";
var fromRecord = /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecord()();
var fromRecordObjCons = /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(Codec_Json_Unidirectional_Value.fromRecordObjNil);
var encoder = /* #__PURE__ */ fromRecord(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ fromRecordObjCons({
    reflectSymbol: function () {
        return "zAppearsFirst";
    }
})()())({
    reflectSymbol: function () {
        return "reqRen";
    }
})()())({
    reflectSymbol: function () {
        return "req";
    }
})()())({
    reflectSymbol: function () {
        return "optRen";
    }
})()())({
    reflectSymbol: function () {
        return "optArr";
    }
})()())({
    reflectSymbol: function () {
        return "opt";
    }
})()())({
    reflectSymbol: function () {
        return "nested";
    }
})()())({
    req: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRequired(Codec_Json_Unidirectional_Value.fromInt),
    reqRen: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRequiredRename("otherName")(Codec_Json_Unidirectional_Value.fromString),
    zAppearsFirst: /* #__PURE__ */ Codec_Json_Unidirectional_Value["fromRequired$prime"](Codec_Json_Unidirectional_Value.fromString),
    opt: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromOption(Codec_Json_Unidirectional_Value.fromString),
    optRen: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromOptionRename("otherName2")(Codec_Json_Unidirectional_Value.fromString),
    optArr: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromOptionArray(Codec_Json_Unidirectional_Value.fromString),
    nested: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRequired(/* #__PURE__ */ fromRecord(/* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRecordObjCons(/* #__PURE__ */ fromRecordObjCons({
        reflectSymbol: function () {
            return "other";
        }
    })()())({
        reflectSymbol: function () {
            return "foo";
        }
    })()())({
        other: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromRequired(Codec_Json_Unidirectional_Value.fromBoolean),
        foo: /* #__PURE__ */ Codec_Json_Unidirectional_Value.fromOption(Codec_Json_Unidirectional_Value.fromBoolean)
    }))
});
var test = function (j) {
    return encoder(j);
};
export {
    encoder,
    test
};
