// Generated by purs version 0.15.10
import * as Codec_Json_Unidirectional_Value from "../Codec.Json.Unidirectional.Value/index.js";
var decoder = Codec_Json_Unidirectional_Value.toString;
var test = function (j) {
    return decoder(j);
};
export {
    decoder,
    test
};
